utility/urls.py
from django.contrib import admin
from django.urls import path
from workshop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.basic_home, name='home'),
    path('new_work_request/',views.new_work_request, name='new_work_request'),
    path('request_page/<int:work_request_id>', views.request_page, name='request_page'),
    path('status_update/', views.status_update_page, name='status_update_page'),
    path('status_update/<int:task_id>/', views.status_update, name='status_update'),
    path('calculate_workload/', views.calculate_workload, name='calculate_workload'),

]

workshop/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Expertise(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Worker(models.Model):
    name=models.CharField(max_length=100)
    WORKER_TYPE_CHOICES = [
        ('Local','Local'),
        ('Expat','Expat')
    ]
    worker_type = models.CharField(max_length=10, choices=WORKER_TYPE_CHOICES)
    pay_rate = models.FloatField()
    expertise = models.ManyToManyField(Expertise)

    def __str__(self):
        return self.name


class WorkRequest(models.Model):
    UNIT_CHOICES = [
        ('FM1', 'FM1'),
        ('FM2', 'FM2'),
        ('FMM', 'FMM'),
        ('HO', 'Head Office'),
        ('KNT', 'KNT'),
        ('NP5', 'NP5'),
        ('SML', 'SML'),
    ]
    unit = models.CharField(max_length=10, choices=UNIT_CHOICES)
    DEPT_CHOICES = [
        ('',''),
        ('AUTO','Automotive'),
        ('ELEC','Electrical'),
        ('HR','HR'),
        ('MAINT','Maintenance'),
        ('RND','RnD'),
        ('UTL','Utility'),
    ]
    department = models.CharField(max_length=50, blank=True, choices=DEPT_CHOICES)
    date = models.DateField()
    requester = models.CharField(max_length=50)

    def __str__(self):
        return f"Request from '{self.requester}', '{self.unit}' received on '{self.date}'"


class Task(models.Model):
    work_request = models.ForeignKey(WorkRequest, related_name='tasks', on_delete=models.CASCADE)
    description = models.TextField()
    URGENCY_CHOICES=[
        (1,'1 Week'),
        (2,'3 Days'),
        (3,'1 Day')
    ]
    urgency = models.IntegerField(choices=URGENCY_CHOICES)
    quantity = models.IntegerField()
    TASK_TYPE_CHOICES = [
        (1,'Repair'),
        (2,'Modification'),
        (3,'Fabrication'),
        (4,'Other')
    ]
    task_type = models.IntegerField(choices=TASK_TYPE_CHOICES)
    machining = models.BooleanField(default=False)
    assessment_hours = models.FloatField(blank=True, null=True)
    assessment_time = models.DurationField(blank=True, null=True)
    is_planned = models.BooleanField(default=False)

    STATE_CHOICES = [
        (1,'New'),
        (2,'Queued'),
        (3,'Back Load'),
        (4,'Awaiting Material'),
        (5,'In Progress'),
        (6,'Completed'),
        (7,'Cancelled')
    ]
    current_status = models.IntegerField(choices=STATE_CHOICES, default=1)

    # def current_status(self):
    #     latest_state = self.stateduration_set.order_by('-start_time').first()
    #     return latest_state.get_state_display()


    
    def save(self, *args, **kwargs):

        super(Task, self).save(*args, **kwargs)

        #Checks if a StateDuration entry already exists
        if not self.stateduration_set.exists():
            #Create a new StateDuration entry with status "NEW"
            StateDuration.objects.create(
                task = self,
                state = 1,
                start_time = self.work_request.date,
                normal_duration = timezone.timedelta(minutes=0),
                overtime_duration = timezone.timedelta(minutes=0)
            )
            self.current_status = 1 
        
        
        latest_state = self.stateduration_set.order_by('-start_time').first()
        if latest_state:
            self.current_status = latest_state.state
            super(Task, self).save(*args, **kwargs)


        


class StateDuration(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    STATE_CHOICES = [
        (1,'New'),
        (2,'Queued'),
        (3,'Back Load'),
        (4,'Awaiting Material'),
        (5,'In Progress'),
        (6,'Completed'),
        (7,'Cancelled')
    ]
    state = models.IntegerField(choices=STATE_CHOICES)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True, blank=True)
    normal_duration = models.DurationField(null=True, blank=True)
    overtime_duration = models.DurationField(null=True, blank=True)
    workers = models.ManyToManyField(Worker)


class MaterialPurchase(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    material_name = models.CharField(max_length=100)
    quantity = models.FloatField()
    received = models.BooleanField(default=False)


class TaskReport(models.Model):
    task = models.OneToOneField(Task, on_delete=models.CASCADE)
    total_time_spent = models.DurationField()
    total_manpower_cost = models.FloatField()
    total_material_cost = models.FloatField()


class MaterialUsed(models.Model):
    report = models.ForeignKey(TaskReport, related_name='materials_used', on_delete=models.CASCADE)
    material_name = models.CharField(max_length=100)
    quantity = models.FloatField()
    cost = models.FloatField()


class CachedCalculation(models.Model):
    date = models.DateField(unique=True, help_text="Date for which calculation is made")
    machining_workload = models.FloatField(help_text="Cummulative assessment time for all active machining tasks")
    last_updated = models.DateTimeField(auto_now=True)

    def __str__ (self):
        return f"Calculation(s) for {self.date}"
    

templates/basic_home.html
{% extends 'main.html' %}
{% load static %}


{% block content %}

<p>Home Page</p>

{% endblock content %}

templates/request_page.html
{% extends 'main.html' %}

{% block content %}

<!-- Section 1 : Work Request Details -->

<div class="container mt-5">
    <div class="card shadow py-2">
        <div class="card-header bg-white">
            <h4>Work Request Details</h4>
        </div>
        <div class="card-body">
            <form>
                <div class="row mt-2">
                    <div class="col">
                        <div class="form-group">
                            <label for="workRequestId" class="form-label">Work Request ID</label>
                            <input class="form-control" type="text" id="workRequestId" value="{{ work_request.id }}" readonly>
                        </div>
                    </div>
                    <div class="col-4"></div>
                    <div class="col">
                        <div class="form-group">
                            <label class="form-label" for="date">Date</label>
                            <input class="form-control" type="text" id="date" value="{{ work_request.date }}" readonly>
                        </div>
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col">
                        <div class="form-group">
                            <label class="form-label" for="unit">Unit</label>
                            <input class="form-control" type="text" id="unit" value="{{ work_request.get_unit_display }}" readonly>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label class="form-label" for="department">Department</label>
                            <input class="form-control" type="text" id="department" value="{{ work_request.get_department_display }}" readonly>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label class="form-label" for="requester">Requester</label>
                            <input class="form-control" type="text" id="requester" value="{{ work_request.requester }}" readonly>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Section 2 Machining Tasks List -->

<div class="container mt-5">
    <div class="card shadow">
        <div class="card-header" style="background-color: #D0E8F2;">
            <h4>Machining Tasks</h4>
        </div>
        <div class="card-body">
            <div class="table-responsive table mt-2" role="grid"></div>
                <table class="table my-0">
                    <!-- Headers -->
                    <thead>
                        <tr>
                            <th>Description</th>
                            <th>Urgency</th>
                            <th>Assessment Time</th>
                            <th>Quantity</th>
                            <th>Job Type</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <!-- Body -->
                    <tbody>
                        {% for task in machining_tasks %}
                        <tr>
                            <td class="description-cell">{{ task.description }}</td>
                            <td>{{ task.get_urgency_display }}</td>
                            <td>{{ task.assessment_time }}</td>
                            <td>{{ task.quantity }}</td>
                            <td>{{ task.get_task_type_display }}</td>
                            <td>{{ task.get_current_status_display }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>    
    </div>
</div>

<!-- Section 3: Non Machining Tasks -->

<div class="container mt-5">
    <div class="card shadow py-2">
        <div class="card-header bg-white">
            <h4>Non-Machining Task</h4>
        </div>
        <div class="card-body">
            <div class="table-responsive table mt-2" role="grid">
                <table class="table my-0">
                    <!-- Headers -->
                    <thead>
                        <tr>
                            <th>Description</th>
                            <th>Urgency</th>
                            <th>Assessment Time</th>
                            <th>Quantity</th>
                            <th>Job Type</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <!-- Body -->
                    <tbody>
                        {% for task in non_machining_tasks %}
                        <tr>
                            <td class="description-cell">{{ task.description }}</td>
                            <td>{{ task.get_urgency_display }}</td>
                            <td>{{ task.assessment_time }}</td>
                            <td>{{ task.quantity }}</td>
                            <td>{{ task.get_task_type_display }}</td>
                            <td>{{ task.get_current_status_display }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Section 4: New Task Form -->

<div class="container mt-5">
    <div class="card shadow py-2">
        <div class="card-header bg-white">
            <h4>Add New Task</h4>
        </div>
        <div class="card-body">
            <form action="{% url 'request_page' work_request.id %}" method="post">
                {% csrf_token %}

                <div class="row d-flex justify-content-between mt-2">
                    <div class="col-5 ">
                        <!-- Description Field -->
                        <label for="{{ new_task_form.description.id_for_label }}" class="form-label">Description</label>
                        <textarea  class="form-control" name="{{ new_task_form.description.name }}" id="{{ new_task_form.description.id_for_label }}" rows="4"></textarea>
                        <!-- Urgency Field -->
                        <label for="{{ new_task_form.urgency.id_for_label }}" class="form-label mt-3">Urgency</label>
                        <select class="form-select" name="{{ new_task_form.urgency.name }}" id="{{ new_task_form.urgency.id_for_label }}">
                            {% for value, label in new_task_form.fields.urgency.choices %}
                            <option value="{{ value }}">{{ label }}</option>
                            {% endfor %}
                        </select>
                        <!-- Quantity -->
                        <label for="{{ new_task_form.quantity.id_for_label }}" class="form-label mt-3">Quantity</label>
                        <input type="number" name="{{ new_task_form.quantity.name }}" id="{{ new_task_form.quantity.id_for_label }}" class="form-control">
                    </div>
                    <div class="col-5">
                        <!--Assessment Hours Field-->
                        <label for="{{ new_task_form.assessment_hours.id_for_label }}" class="form-label">Assessment Time (in Hours)</label>
                        <input type="number" step="0.1" class="form-control" name="{{ new_task_form.assessment_hours.name }}" id="{{ new_task_form.assessment_hours.id_for_label }}">
                        <!-- Task Type Field -->
                        <label for="{{ new_task_form.task_type.id_for_label }}" class="form-label mt-3">Task Type</label>
                        <select name="{{ new_task_form.task_type.name }}" id="{{ new_task_form.task_type.id_for_label }}" class="form-select">
                            {% for value, label in new_task_form.fields.task_type.choices %}
                            <option value="{{ value }}">{{ label }}</option>
                            {% endfor %}
                        </select>
                        <!-- Machining Field -->
                        <div class="form-check mt-3">
                            <input type="checkbox" class="form-check-input" id="{{ new_task_form.machining.id_for_label }}" name="{{ new_task_form.machining.name }}">
                            <label class="form-check-label" for="{{ new_task_form.machining.id_for_label }}">Machining</label>
                        </div>

                        <!-- Submit Button -->
                        <button type="submit" class="btn btn-primary mt-4 w-100">Create Task</button>

                    </div>
                </div>
            </form>
        </div>

    </div>
</div>








 
{% endblock content %}

templates/status_update.html
{% extends 'main.html' %}

{% block content %}

<!-- Section 1 :  Work Request and Task Info -->

<div class="container mt-5">
    <div class="row">

        <div class="col-6">
            <!-- Work Request Info Card -->
            <div class="card shadow">
                <div class="card-header header-2">
                    <h5>Work Request Details</h5>
                </div>
                <div class="card-body">
                    <form>
                        <!-- Work Request ID -->
                        <div class="d-flex justify-content-between">
                            <label for="workRequestId" class="form-label col-4">Work Request ID:</label>
                            <input type="text" class="form-control" value="{{ work_request.id }}" readonly>
                        </div>
                        <!-- Date -->
                        <div class="d-flex justify-content-between mt-3">
                            <label for="date" class="form-label col-4">Date:</label>
                            <input type="text" class="form-control" value="{{ work_request.date }}" readonly>
                        </div>
                        <!-- Unit -->
                        <div class="d-flex justify-content-between mt-3">
                            <label for="unit" class="form-label col-4">Unit:</label>
                            <input type="text" class="form-control" value="{{ work_request.get_unit_display }}" readonly>
                        </div>
                        <!-- Department -->
                        <div class="d-flex justify-content-between mt-3">
                            <label for="department" class="form-label col-4">Department:</label>
                            <input type="text" class="form-control" value="{{ work_request.get_department_display }}" readonly>
                        </div>
                        <!-- Requester -->
                        <div class="d-flex justify-content-between mt-3">
                            <label for="requester" class="form-label col-4">Requester:</label>
                            <input type="text" class="form-control" value="{{ work_request.requester }}" readonly>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-6 ml-3">
            <!-- Task Info Card -->
            <div class="card shadow">
                <div class="card-header header-2">
                    <h5>Task Details</h5>
                </div>
                <div class="card-body">
                    <form>
                        <!-- Description -->
                        <div class="form-group justify-content-between">
                            <label for="description" class="form-label">Description:</label>
                            <textarea class="form-control" rows="2" readonly>{{ task.description }}</textarea>
                        </div>
                        <!-- Urgency -->
                        <div class="d-flex justify-content-between mt-3">
                            <label for="urgency" class="form-label col-4">Urgency:</label>
                            <input type="text" class="form-control" value="{{ task.get_urgency_display }}" readonly>
                        </div>
                        <!-- Quantity -->
                        <div class="d-flex justify-content-between mt-3">
                            <label for="quantity" class="form-label col-4">Quantity:</label>
                            <input type="text" class="form-control" value="{{ task.quantity }}" readonly>
                        </div>
                        <!-- Machining -->
                        <div class="d-flex mt-3">
                            <label for="machining" class="form-label col-4">Machining</label>
                            <input type="checkbox" class="form-check-input" {% if task.machining %} checked {% endif %} readonly disabled>
                        </div>
                        <!-- Assessment Time -->
                        <div class="d-flex justify-content-between mt-3">
                            <label for="quantity" class="form-label col-4">Assessment Time:</label>
                            <input type="text" class="form-control" value="{{ task.assessment_time }}" readonly>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>



<!-- Section 2 : Status History -->
<div class="container mt-5">
    <div class="card shadow">
        <div class="card-header header-4">
            <h5>Status History</h5>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Status</th>
                        <th>Start Time</th>
                        <th>End Time</th>
                        <th>Normal Duration</th>
                        <th>Overtime Duration</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for status in status_history %}
                    <tr>
                        <td>{{ status.get_state_display }}</td>
                        <td>{{ status.start_time }}</td>
                        <td>{{ status.end_time }}</td>
                        <td>{{ status.normal_duration }}</td>
                        <td>{{ status.overtime_duration }}</td>
                        <td>
                            <!-- End Time Button for only "In Progress" without end_time -->
                            {% if status.state == 5 and status.end_time == None %}
                            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#updateEndTimeModal-{{status.id}}">
                                End Time
                            </button>


                            <!-- End Time Modal -->
                            <div class="modal fade" id="updateEndTimeModal-{{status.id}}" tabindex="-1" aria-labelledby="updateEndTimeModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="updateEndTimeModalLabel">Set End Time</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <form action="{% url 'status_update' task.id %}" method="post">
                                                {% csrf_token %}
                                                <input type="hidden" name="update_end_time" value="True">
                                                <input type="hidden" name="status.id" value="{{ status.id }}">
                                                <!-- Date Picker -->
                                                <input type="date" name="end_date" id="end_date" class="form-control">
                                                <!-- Time Picker -->
                                                <input type="time" name="end_time" id="end_time" class="form-control mt-1">

                                                <div class="modal-footer">
                                                    <button type="submit" class="btn btn-primary">Update</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


<!-- Section 3 : Status Update Form -->
<div class="container mt-5">
    <div class="card shadow">
        <div class="card-header header-4">
            <h5>Status Update</h5>
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'status_update' task.id %}">
                {% csrf_token %}

                <div class="row d-flex justify-content-between">
                <div class="col-5">
                <!-- State Field -->
                <div class="mb-3">
                    <label for="state" class="form-label">Status</label>
                    {{ form.state }}
                </div>
                <!-- Start Time Field -->
                <div class="mb-3">
                    <label for="start_date">Start Date / Time</label>
                    <input type="date" class="form-control" id="start_time_date" name="start_time_date">
                    <input type="time" class="form-control mt-1" id="start_time_time" name="start_time_time">
                </div>
                </div>

                <div class="col-5">
                    <!-- Workers Checkbox -->
                    <div class="mb-3">
                        <label for="workers" class="form-label">Technicians</label>
                        {{ form.workers }}
                    </div>

                    <button type="submit" class="btn btn-primary mt-4 w-100">Update Status</button>
                </div>
                </div>
            </form>
        </div>

    </div>
</div>




{% endblock content %}

templates/status_update_page.html
{% extends 'main.html' %}
{% block content %}

<!-- Filters Section -->
<div class="container mt-4">
    <div class="card shadow">
        <div class="card-header header-3">
            <h4>Task Filters</h4>
        </div>
        <div class="card-body">
            <form action="" method="GET">
                {{ task_filter_form.as_p }}
                <button type="submit" class="btn btn-primary">Apply Filters</button>
                <a href="{% url 'status_update_page' %}" class="btn btn-secondary">Reset Filters</a>
            </form>
        </div>
    </div>
</div>

<!-- Task List Section -->
<div class="container">
    <div class="card mt-5 shadow">
        <div class="card-header header-4">
            <h4>Available Tasks for Today</h4>
        </div>
        <div class="card-body">
            <table class="table-responsive table mt-2" role="grid">
                <thead>
                    <tr>
                        <th>Description</th>
                        <th>Urgency</th>
                        <th>Unit</th>
                        <th>Dept.</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in filtered_tasks %}
                    <tr>
                        <td class="description-cell">{{ task.description }}</td>
                        <td>{{ task.get_urgency_display }}</td>
                        <td>{{ task.work_request.get_unit_display }}</td>
                        <td>{{ task.work_request.get_department_display }}</td>
                        <td>{{ task.get_current_status_display }}</td>
                        <td>
                            <a href="{% url 'status_update' task.id %}" target="_blank" class="
                            btn btn-primary">Update Status</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>



{% endblock content %}